[tool.black]
line-length = 95
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 95
src_paths = ["aoc2021"]

[tool.pytest.ini_options]


[tool.mypy]
ignore_missing_imports = true
allow_redefinition = true
files = "aoc2021"